config/routes.rb
SellContent::Application.routes.draw do

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  devise_for :users
  root :to => 'home#index'
  get "/checkout/:code" => "home#checkout", :as => :checkout
  post "/checkout/:code" => "home#checkout", :as => :checkout

  get '/profile' => "profile#upload", :as => :profile_upload
  post '/profile' => "profile#upload", :as => :profile_upload
  get '/profile/c/:code' => "profile#edit_product", :as => :profile_product
  put '/profile/c/:code' => "profile#update_product", :as => :profile_product_update
  delete '/profile/c/:code' => "profile#delete_product", :as => :profile_product_delete
  put '/profile/c/:code/save_content' => "profile#save_content", :as => :profile_product_save_content
  delete '/profile/c/:code/save_content/:id' => "profile#delete_content", :as => :profile_product_delete_content
  delete '/profile/c/:code/save_cover/:id' => "profile#delete_cover", :as => :profile_product_delete_cover

  get '/profile/products' => "profile#products", :as => :profile_products
  get 'profile/products/new' => "profile#new_product" , :as => :new_profile_product
  post 'profile/products/create' => "profile#create_product" , :as => :create_profile_product

  get '/profile/bought_orders' => "profile#bought_orders", :as => :profile_bought_orders
  get '/profile/sold_orders' => "profile#sold_orders", :as => :profile_sold_orders
  get '/profile/bought_order/:id' => "profile#bought_order", :as => :profile_bought_order
  get '/profile/bought_order/:id/download' => 'profile#download_order' , :as => :profile_download_order
  get '/profile/sold_order/:id' => "profile#sold_order", :as => :profile_sold_order

  resources :products
  resources :orders
  resources :tasks

  get "/:code" => "home#from_code", :as => :from_code

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_filter :authenticate_user!, :only => :checkout
  layout :action_layout

  def index

  end


  def from_code
    @product = Product.active.find_by_code(params[:code])
    if @product.blank?
      flash[:error] = "Page not found"
      redirect_to root_path and return
    end
  end

  def checkout
    if request.get?
      @order = Order.new
      @product = Product.active.find_by_code(params[:code])
      @order.product = @product
    else
      @order = Order.new(params[:order])
      @product = Product.active.find_by_code(params[:code])
      @order.product = @product
      @order.buyer_id = current_user.id
      if @order.save_with_payment
        redirect_to profile_bought_order_path(@order)
      else
        flash[:error] = @order.errors.full_messages.first
        render 'checkout'
      end
    end
  end

  def action_layout
    if action_name == "from_code"
      "sell"
    else
      "application"
    end
  end
end

app/views/home/checkout.html.erb
<div class="profieldiv">
  <h6>Payment</h6>
</div>
<div class="clearboth"></div>
<div class="settingsblock leftfull2">


  <%= form_for @order, :url => checkout_path(@product.code), :method => :post, :html => {:id => "new_order"} do |f| %>
      <%= f.hidden_field :stripe_card_token %>

      <div class="settingsinput">
        <%= label_tag :card_number, "Credit Card Number" %>
        <%= text_field_tag :card_number, nil, name: nil, :class => "shartabinput" %>
      </div>
      <div class="settingsinput">
        <%= label_tag :card_code, "Security Code on Card (CVV)" %>
        <%= text_field_tag :card_code, nil, name: nil, :class => "shartabinput" %>
      </div>
      <div class="settingsinput">
        <%= label_tag :card_month, "Card Expiration" %>
        <%= select_month nil, {add_month_numbers: true}, {name: nil, id: "card_month"} %>
        <%= select_year nil, {start_year: Date.today.year, end_year: Date.today.year+15}, {name: nil, id: "card_year"} %>
      </div>
      <div id="stripe_error">
        <noscript>JavaScript is not enabled and is required for this form. First enable it in your web browser settings.
        </noscript>
      </div>
      <div class="settingsinput whitebg bdBnone">
        <label><%= number_to_currency @product.price, :unit => "$" %></label>
        <%= f.submit "Place my order",class:"uploastyle2" %>
        <%= link_to "Cancel", from_code_path(@product.code), :class => "uploastyle3" %>
      </div>
  <% end %>
  <div class="clearboth"></div>
</div>

<style>
 #stripe_error{
     color: red;
     font-size: 15px;
 }
</style>

app/views/home/from_code.html.erb
<div class="prodcutimg">

      <%= image_tag cover_image(@product), :width => "480", :height => "560", :alt => "Product image" %>

  <div class="pricetag"><%= number_to_currency @product.price %></div>
</div>

<div class="prodcut_content">
  <div class="buyitbutton">

    <%= link_to "Buy it", checkout_path(@product.code), class: "buttonformobile" %>
    <span> Payments are 100% secure </span>

  </div>
  <div class="product_detailsell">
    <h5><%= @product.name %></h5>

    <p class="description"><%= @product.description %></p>
  </div>


  <div class="clearboth"></div>
</div>

<div class="graysectionblock">


  <div class="forsaveto"><span>Contents</span></div>

  <% @product.contents.each do |c| %>
      <div class="clearboth filetype_size">
        <p>File: <%= c.attachment_file_name %> &nbsp;&nbsp;|&nbsp;&nbsp;Size: <%= c.attachment_file_size %> KB</p>
      </div>

  <% end %>



  <!--<div class="buttons_mid">-->


    <!--<a href="#" class="uploastyle3 disablebut"><img src="/assets/dropbox.png" width="13" height="13" alt="Dropbox"/>&nbsp;Dropbox&nbsp;-->
    <!--</a>-->
    <!--<a href="#" class="uploastyle3 disablebut"><img src="/assets/kindle.png" width="13" height="13" alt="Dropbox"/>&nbsp;Kindle&nbsp;-->
    <!--</a>-->
    <!--<a href="#" class="uploastyle3 disablebut"><img src="/assets/download_icon2.png" alt="Download"/>&nbsp;Download&nbsp;-->
    <!--</a>-->
  <!--</div>-->

  <!--<div class="forsaveto"><span>Send to your kindle...</span></div>-->

  <!--<div class="inputblockrange">-->
    <!--<input name="" type="text"/>-->

    <!--<div class="totext">@kindle.com</div>-->


  <!--</div>-->

  <!--<div class="clearboth"><a href="#" class="buttonformobile">&nbsp;Send&nbsp;</a></div>-->

</div>

<div class="leftdivlogo">
  <%= link_to image_tag(asset_path("logo.png")),'#', :height => "41" , :width => "37", :border => "0" %>

</div>


<div class="clearboth"></div>

app/views/home/index.html.erb
selam