config/routes.rb
SellContent::Application.routes.draw do

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  devise_for :users
  root :to => 'home#index'
  get "/checkout/:code" => "home#checkout", :as => :checkout
  post "/checkout/:code" => "home#checkout", :as => :checkout

  get '/profile' => "profile#upload", :as => :profile_upload
  post '/profile' => "profile#upload", :as => :profile_upload
  get '/profile/c/:code' => "profile#edit_product", :as => :profile_product
  put '/profile/c/:code' => "profile#update_product", :as => :profile_product_update
  delete '/profile/c/:code' => "profile#delete_product", :as => :profile_product_delete
  put '/profile/c/:code/save_content' => "profile#save_content", :as => :profile_product_save_content
  delete '/profile/c/:code/save_content/:id' => "profile#delete_content", :as => :profile_product_delete_content
  delete '/profile/c/:code/save_cover/:id' => "profile#delete_cover", :as => :profile_product_delete_cover

  get '/profile/products' => "profile#products", :as => :profile_products
  get 'profile/products/new' => "profile#new_product" , :as => :new_profile_product
  post 'profile/products/create' => "profile#create_product" , :as => :create_profile_product

  get '/profile/bought_orders' => "profile#bought_orders", :as => :profile_bought_orders
  get '/profile/sold_orders' => "profile#sold_orders", :as => :profile_sold_orders
  get '/profile/bought_order/:id' => "profile#bought_order", :as => :profile_bought_order
  get '/profile/bought_order/:id/download' => 'profile#download_order' , :as => :profile_download_order
  get '/profile/sold_order/:id' => "profile#sold_order", :as => :profile_sold_order

  resources :products
  resources :orders
  resources :tasks

  get "/:code" => "home#from_code", :as => :from_code

end

app/views/layouts/_navbar.html.erb
<% if current_user %>
    <div class="headericondiv">
      <ul>
        <li>
          <div class="iocntopdiv">
            <div class="iconshow">
              <a href="#"><img src="/assets/topicon01.png" border="0" alt="" width="22" height="20"/></a></div>
            <div class="textshow">
              <a href="#">Balance</a>
            </div>
          </div>
        </li>
        <li>
          <div class="iocntopdiv">
            <div class="iconshow">
              <a href="#"><img src="/assets/topicon02.png" border="0" alt="" width="22" height="20"/></a></div>
            <div class="textshow"><%= link_to "Products", '/profile/products' %></div>
          </div>
        </li>

        <li>
          <div class="iocntopdiv">
            <div class="iconshow">
              <a href="#"><img src="/assets/topicon03.png" border="0" alt="" width="22" height="20"/></a></div>
            <div class="textshow"><a href="#">Task</a></div>
          </div>
        </li>

        <li>
          <div class="iocntopdiv">
            <div class="iconshow">
              <a href="#"><img src="/assets/topicon04.png" border="0" alt="" width="22" height="20"/></a></div>
            <div class="textshow"><a href="#">Inbox</a></div>
          </div>
        </li>

        <li>
          <div class="iocntopdiv">
            <div class="iconshow">
              <a href="#"><img src="/assets/topicon05.png" border="0" alt="" width="22" height="20"/></a></div>
            <div class="textshow"><a href="#">Reports</a></div>
          </div>
        </li>

        <li>
          <div class="iocntopdiv">
            <div class="iconshow">
              <a href="#"><img src="/assets/topicon06.png" border="0" alt="" width="22" height="20"/></a></div>
            <div class="textshow"><a href="#">Notification</a></div>
          </div>
        </li>
        <li>
          <div class="iocntopdiv">
            <div class="iconshow">
              <a href="#"><img src="/assets/topicon07.png" border="0" alt="" width="22" height="20"/></a></div>
            <div class="textshow"><a href="#">Settings</a></div>
          </div>
        </li>
      </ul>
    </div>

    <div class="userboxright">
      <div class="userimgshow">
        <a href="#">
          <img src="<%= current_user.gravatar_url %>" border="0" alt="" width="63" height="65" class="circle"/></a>
      </div>
      <div class="userdelisdiv">

        <div class="singdiv">
          <div class="singshowbox">
            <div class="singicon">
              <a href="<%= destroy_user_session_path %>" data-method='delete'><img src="/assets/singicon01.png" border="0" alt="" width="15" height="13"/>
              </a></div>
            <div class="singtxt"><a href="<%= destroy_user_session_path %>" data-method='delete'>Sign Out</a></div>
          </div>
          <div class="singshowbox">
            <div class="singicon">
              <a href="#"><img src="/assets/helpicon.png" border="0" alt="" width="13" height="13"/> </a></div>
            <div class="singtxt"><a href="#">Help</a></div>
          </div>
        </div>
      </div>
    </div>
<% else %>
    <div class="headericondiv">
    </div>
    <div class="userboxright">
      <div class="userdelisdiv">
        <div class="singdiv">
          <div class="singshowbox">
            <div class="singicon">
              <a href="<%= new_user_session_path %>"><img src="/assets/singicon01.png" border="0" alt="" width="15" height="13"/>
              </a></div>
            <div class="singtxt"><a href="<%= new_user_session_path %>">Sign In</a></div>
          </div>
          <div class="singshowbox">
            <div class="singicon">
              <a href="#"><img src="/assets/helpicon.png" border="0" alt="" width="13" height="13"/> </a></div>
            <div class="singtxt"><a href="#">Help</a></div>
          </div>
        </div>
      </div>
    </div>
<% end %>

app/views/layouts/_social.html.erb
<div id="fb-root"></div>
<script>(function (d, s, id) {
    var js, fjs = d.getElementsByTagName(s)[0];
    if (d.getElementById(id)) return;
    js = d.createElement(s);
    js.id = id;
    js.src = "//connect.facebook.net/tr_TR/all.js#xfbml=1&appId=132131670158185";
    fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

<script>!function (d, s, id) {
    var js, fjs = d.getElementsByTagName(s)[0], p = /^http:/.test(d.location) ? 'http' : 'https';
    if (!d.getElementById(id)) {
        js = d.createElement(s);
        js.id = id;
        js.src = p + '://platform.twitter.com/widgets.js';
        fjs.parentNode.insertBefore(js, fjs);
    }
}(document, 'script', 'twitter-wjs');</script>

app/views/layouts/application.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
  <title><%= content_for?(:title) ? yield(:title) : "AirSpace" %></title>
  <%= csrf_meta_tags %>
  <%= javascript_include_tag "https://js.stripe.com/v1/" %>
  <%= tag :meta, :name => "stripe-key", :content => STRIPE_PUBLIC_KEY %>
  <%= stylesheet_link_tag "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
</head>

<body>
<%= render :partial => "layouts/social" %>
<div class="warpperfull">
  <div class="headermid">
    <div class="headerdelis">
      <div class="logodiv"><a href="#"><img src="/assets/logo.png" border="0" alt="" width="56" height="57"/></a></div>
      <%= render :partial => "layouts/navbar" %>
    </div>
  </div>
</div>
<div class="clearboth"></div>
<% if @layout == :sell %>
    <div class="informationdiv2">
      <%= yield %>
    </div>
<% else %>
    <div class="conntendmid">
      <div class="contentdelis">
        <%= bootstrap_flash %>
        <div class="<%= content_for?(:container_div_class) ? yield(:container_div_class) : 'informationdiv' %>">
          <div class="<%= content_for?(:container_div_class) ? yield(:container_div_class) : 'productdiv' %>">
            <%= yield %>
            <div class="clearboth"></div>
          </div>
        </div>
      </div>
    </div>
<% end %>

<div class="footerfull">
  <div class="footermid">
    <div class="fooermater">2014 &copy; Airspace
      <div class="shareiconsfooter">
        <a href="#"><img src="/assets/share_facebook.png" width="28" height="28" alt="Share on Facebook" title="Share with Facebook"/></a>
        <a href="#"><img src="/assets/share_twitter.png" width="28" height="28" alt="Share on Twitter" title="Share with Twitter"/></a>
        <a href="#"><img src="/assets/share_blog.png" width="28" height="28" alt="Share on Twitter" title="Share on Blog"/></a>


      </div>
    </div>
  </div>
</div>
 <%= render :partial => 'layouts/social' %>
</body>
</html>

app/views/layouts/application_.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
  <title><%= content_for?(:title) ? yield(:title) : "AirSpace" %></title>
  <%= csrf_meta_tags %>
  <%= javascript_include_tag "https://js.stripe.com/v1/" %>
  <%= tag :meta, :name => "stripe-key", :content => STRIPE_PUBLIC_KEY %>
  <%= stylesheet_link_tag "application", :media => "all" %>
  <%= javascript_include_tag "application" %></head>

<body>
<%= render :partial => "layouts/social" %>
<div class="warpperfull">
  <div class="headermid">
    <div class="headerdelis">
      <div class="logodiv"><a href="#"><img src="/assets/logo.png" border="0" alt="" width="56" height="57"/></a></div>
      <div class="headericondiv">
        <ul>


          <li>
            <div class="iocntopdiv">
              <div class="iconshow">
                <a href="#"><img src="/assets/topicon01.png" border="0" alt="" width="22" height="20"/></a></div>
              <div class="textshow">
                <a href="#">Balance</a>
              </div>
            </div>
          </li>
          <li>
            <div class="iocntopdiv">
              <div class="iconshow">
                <a href="#"><img src="/assets/topicon02.png" border="0" alt="" width="22" height="20"/></a></div>
              <div class="textshow"><%= link_to "Products", profile_products_path %></div>
            </div>
          </li>

          <li>
            <div class="iocntopdiv">
              <div class="iconshow">
                <a href="#"><img src="/assets/topicon03.png" border="0" alt="" width="22" height="20"/></a></div>
              <div class="textshow"><a href="#">Task</a></div>
            </div>
          </li>

          <li>
            <div class="iocntopdiv">
              <div class="iconshow">
                <a href="#"><img src="/assets/topicon04.png" border="0" alt="" width="22" height="20"/></a></div>
              <div class="textshow"><a href="#">Inbox</a></div>
            </div>
          </li>

          <li>
            <div class="iocntopdiv">
              <div class="iconshow">
                <a href="#"><img src="/assets/topicon05.png" border="0" alt="" width="22" height="20"/></a></div>
              <div class="textshow"><a href="#">Reports</a></div>
            </div>
          </li>

          <li>
            <div class="iocntopdiv">
              <div class="iconshow">
                <a href="#"><img src="/assets/topicon06.png" border="0" alt="" width="22" height="20"/></a></div>
              <div class="textshow"><a href="#">Notification</a></div>
            </div>
          </li>
          <li>
            <div class="iocntopdiv">
              <div class="iconshow">
                <a href="#"><img src="/assets/topicon07.png" border="0" alt="" width="22" height="20"/></a></div>
              <div class="textshow"><a href="#">Settings</a></div>
            </div>
          </li>
        </ul>
      </div>
      <div class="userboxright">
        <div class="userimgshow">
          <a href="#"><img src="/assets/userimgtop.png" border="0" alt="" width="63" height="65"/></a></div>
        <div class="userdelisdiv">

          <div class="singdiv">
            <div class="singshowbox">
              <div class="singicon">
                <a href="#"><img src="/assets/singicon01.png" border="0" alt="" width="15" height="13"/> </a></div>
              <div class="singtxt"><a href="#">Sign Out</a></div>
            </div>
            <div class="singshowbox">
              <div class="singicon">
                <a href="#"><img src="/assets/helpicon.png" border="0" alt="" width="13" height="13"/> </a></div>
              <div class="singtxt"><a href="#">Help</a></div>
            </div>
          </div>
        </div>
      </div>


    </div>
  </div>
</div>
<div class="conntendmid">
  <div class="contentdelis">
    <div class="informationdiv">
      <div class="productdiv">
        <%= yield %>
        <div class="clearboth"></div>
      </div>
    </div>
  </div>
</div>

<div class="footerfull">
  <div class="footermid">
    <div class="fooermater">2014 &copy; Airspace
      <div class="shareiconsfooter">
        <a href="#"><img src="/assets/share_facebook.png" width="28" height="28" alt="Share on Facebook" title="Share with Facebook"/></a>
        <a href="#"><img src="/assets/share_twitter.png" width="28" height="28" alt="Share on Twitter" title="Share with Twitter"/></a>
        <a href="#"><img src="/assets/share_blog.png" width="28" height="28" alt="Share on Twitter" title="Share on Blog"/></a>


      </div>
    </div>
  </div>
</div>

</body>
</html>

app/views/layouts/sell.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
  <title><%= content_for?(:title) ? yield(:title) : "AirSpace" %></title>
  <%= csrf_meta_tags %>
  <%= javascript_include_tag "https://js.stripe.com/v1/" %>
  <%= tag :meta, :name => "stripe-key", :content => STRIPE_PUBLIC_KEY %>
  <%= stylesheet_link_tag "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
</head>

<body>
<div class="warpperfull">

  <div class="userboxright">
    <div class="userimgshow">
      <a href="#"><img src="<%= @product.user.gravatar_url %>" border="0" alt="" width="63" height="65" class="circle"/></a>
    </div>
    <div class="userdelisdiv">

      <div class="singdiv">
        <div class="sharingicons">
          <div class="singicon">
            <a href="#" class="padicon"><img src="/assets/email_iconbig.png" border="0" alt="" width="28" height="28"/>
            </a></div>
          <div class="singicon">
            <a href="#" class="padicon"><img src="/assets/share_facebook.png" width="28" height="28" alt="Facebook"/>
            </a></div>
          <div class="singicon">
            <a href="#" class="padicon"><img src="/assets/share_twitter.png" border="0" alt="" width="26" height="26"/>
            </a></div>

        </div>

      </div>
    </div>
  </div>

</div>
<div class="clearboth"></div>
<div class="informationdiv2">
  <%= yield %>
</div>

<div class="footerfull">
  <div class="footermid">
    <div class="fooermater">2014 &copy; Airspace

    </div>
  </div>
</div>

</body>
</html>